Adds wiki link to item's image
evansloan/collectionlog.net pull request #60
Opened 2023-04-18 03:32 UTC by dpaskal

This adds a wiki link to items' image/icon in 'Recent items' sections (home page and user page).

Items in the collection log search already have this link so this only adds the link to 'Recent items' sections (On the home page and user page).

Also converted `wrapperClassName` to `const` and assign via ternary operator.

This is a feature I've wanted to see added.

2023-04-19 10:14 UTC, evansloan requested changes
These changes significantly shrink the size of item images. If you can implement these changes while maintaining the original image size I'll get this merged. Everything else looks good.

Before:
![Screenshot 2023-04-19 061139](https://user-images.githubusercontent.com/8287750/233043819-c4e26359-e386-4fef-8e8a-797cf1778d18.png)



After:
![Screenshot 2023-04-19 061148](https://user-images.githubusercontent.com/8287750/233043834-30f7b402-79f7-4d52-a4d1-ae2a7a02d9f9.png)

2023-04-22 00:09 UTC, dpaskal commented
Good catch, I didn't notice.

I have applied the fix for this so the icons look identical now.

2023-04-29 16:39 UTC, dpaskal commented
Is there anything else needed for this PR? @evansloan

2023-04-30 09:07 UTC, evansloan approved these changes

2023-04-30 09:08 UTC, merged